### ISSUE TITLE
LinkedIn Cocoa Pod Missing

### ISSUE THREAD

**Issue by yugalkishoregoyal** [calebd/SimpleAuth#100]
Hi,
Is it available in Cocoa pods or not ? I've read issues on the Linkedin pod and I think its not available in pods yet.
I tried - pod 'SimpleAuth/Linkedin' but it shows error while adding pods.
or do I need to use master only ?

**Comment by mergesort** [comment]
@eryugal: It should be `SimpleAuth/LinkedIn`, with a capital I.

**Comment by yugalkishoregoyal** [comment]
Hi,
Thanks for replying.
It did not worked , I tried all the combination i.e. linkedin , LinkedIn , Linkedin 
![screen_linkedin](https://cloud.githubusercontent.com/assets/12165538/7539047/1a9f5bd8-f559-11e4-823c-97b4ffc5fbc5.PNG)

**Comment by calebd** [comment]
`pod "SimpleAuth/LinkedInWeb"`
