### ISSUE TITLE
Result, Box, and ReactiveCocoa not upgraded to Swift 2?

### ISSUE THREAD

**Issue by lukenewman** [calebd/SimpleAuth#111]
I'm using SimpleAuth to authenticate with LinkedIn. Ever since upgrading to Xcode 7, I've gotten issues with SimpleAuth's dependencies Result, Box, and ReactiveCocoa because they're seemingly not updated to Swift 2 yet. I'm not very well versed with podspecs, but when I look at the SimpleAuth's, none of these are listed as dependencies for SimpleAuth/LinkedIn. The SimpleAuth line in my Podfile is this: `pod 'SimpleAuth/LinkedInWeb'`.

Is there something else I need in my Podfile to specify that I don't need these dependencies? Or is there a different issue I'm not seeing?

**Comment by MaximKeegan** [comment]
Add this to podfile

```
pod 'Box', :head
pod 'Result', :head
```

**Comment by lukenewman** [comment]
That did the trick. I had experimented with the `:head` tag before. Don't know why it didn't work then. Thanks!
