### ISSUE TITLE
Swift, Code 400 response from Instagram

### ISSUE THREAD

**Issue by FridaySG** [calebd/SimpleAuth#118]
Here is my configuration, I'm coding with Xcode 7:

```
SimpleAuth.configuration()["instagram"] = ["**client id***": "****client id*****", SimpleAuthRedirectURIKey: "http://google.com"]
```

Calling SimpleAuth to authorize like this:

```
SimpleAuth.authorize("instagram", options: ["scope" : ["basic", "comments", "likes", "relationships"]], completion: {
    (responseObject : AnyObject!, error : NSError!) -> Void in })
```

In response I receive this error:

```
{
"code": 400,
"error_type": "OAuthException",
"error_message": "You must include a valid client_id, response_type, and redirect_uri parameters"
}
```

Also, when I try to access responseObject in any fashion afterwards, I get an "unresolved identifier" error.
I'm still getting the hang of programming, so any help would be appreciated. Thanks.

**Comment by calebd** [comment]
Your configuration should look something like this:

``` swift
SimpleAuth.configuration()["instagram"] = [
    "client_id": "YOUR_CLIENT_ID_HERE",
    SimpleAuthRedirectURIKey: "YOUR_REDIRECT_URI_HERE"
]
```

Your redirect URI should match the value you provided on the Instagram developer site.

**Comment by FridaySG** [comment]
Yes on the instagram developer site I provided "http://google.com" as the redirect URI as well for testing purposes. Am I interpreting this incorrectly? As in is there more to it than just filling that field and making sure it matches?

**Comment by calebd** [comment]
Cool. Well your original example had `"**client id***"` as the dictionary key which is not correct.

**Comment by FridaySG** [comment]
I'm laughing at myself right now. Thank you very much for your help and patience.

**Comment by calebd** [comment]
Any time! Let me know if you have any other issues!
