### ISSUE TITLE
Google provider

### ISSUE THREAD

**Issue by iamabhiee** [calebd/SimpleAuth#29]
I am trying to add Google provider, but issue is that Google doesn't actually redirect to redirect_url, Normally in all other providers we use webViewhouldStartLoadWithRequest, instead of that we have to use webViewDidFinishLoad. Any suggestions regarding how to implement this without ruining the simplicity of the code ??

**Comment by calebd** [comment]
Apologies for the way late response on this. #84 fixes this.
