### ISSUE TITLE
Twitter-web 

### ISSUE THREAD

**Issue by zackbraksa** [calebd/SimpleAuth#32]
While trying to use Twitter-web, with the following code : 

```
[SimpleAuth authorize:@"twitter-web" completion:^(id responseObject, NSError *error) {
        NSLog(@"%@", responseObject);
        NSLog(@"%@", error);
    }];
```

I get the following error (and the UIWebView doesn't show up): 

```
Error Domain=NSURLErrorDomain Code=-1012 "The operation couldn’t be completed. (NSURLErrorDomain error -1012.)" UserInfo=0xa972a80 {NSErrorFailingURLKey=https://api.twitter.com/oauth/request_token, NSErrorFailingURLStringKey=https://api.twitter.com/oauth/request_token, NSUnderlyingError=0xfc79580 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1012.)"}
```

Even if I made sure to setup the consumer key and the consumer secret !

**Comment by davidchang** [comment]
for future reference, +1 ryohey's correspondence. Setting the Callback URL fixed the issue for me.

The description on that field on Twitter's app management dashboard says, "To restrict your application from using callbacks, leave this field blank."
