### ISSUE TITLE
Swift Rewrite

### ISSUE THREAD

**Issue by calebd** [calebd/SimpleAuth#67]
I have the following goals for a new version of SimpleAuth that solves many of the issues we see today:
- Swift
- Strongly typed provider configurations
- Make `SimpleAuthProvider` a subclass of `NSOperation`
- The `SimpleAuth` class will maintain an instance of `NSOperationQueue` to ensure serial operations
- Favor direct provider interaction over the indirection that is used today
- Keep existing API (deprecated)

**Comment by jsanders67** [comment]
What is the swift implementation of the configuration method. I'm a beginner when it come to objective-c but have been using swift for a couple months. Im just confused on how to configure the Simple Auth with the dictionary I have created with client id and SimpleAythRedirectURIKey

Thanks

**Comment by calebd** [comment]
Something like: `SimpleAuth.configuration()["provider-name"] = [:]`. Just a class method and a dictionary.

**Comment by JinkProject** [comment]
Going to do a Swift re-write of this when I have time. Has it been done before?

**Comment by ejpusa** [comment]
Think most people are using this now: https://github.com/dongri/OAuthSwift
Don't think it's worth your time to re/write, unless for an academic exercise. OAuthSwift it's all done for you.

**Comment by JinkProject** [comment]
@ejpusa Awesome. Thanks!
