### ISSUE TITLE
Error on adding SimpleAuth

### ISSUE THREAD

**Issue by gsrivast31** [calebd/SimpleAuth#80]
On including SimpleAuth via Cocoapods, I am getting following error in Pods-Contakt-LlamaKit : 

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

**Comment by calebd** [comment]
I'm not sure if I can help with this. I don't use `LlamaKit`. Do you have any more output from the build error?

**Comment by gsrivast31** [comment]
Actually, it is being installed due to ReactiveCocoa on which SimpleAuth has a dependency.

**Comment by JinkProject** [comment]
I was about to post this issue as well. Updated SimpleAuth and I believe ReactiveCocoa is dependent on LlamaKit. Taking this over to ReactiveCocoa to see if they know of it as well.

**Comment by JinkProject** [comment]
So I found a solution. Just install the latest version of Cocoapods and it will remove Llamakit and install ReactiveCocoa 2.4.4.

**Comment by calebd** [comment]
I don't think ReactiveCocoa is dependent on LlamaKit. LlamaKit is all Swift and you can't even ship Swift code in CocoaPods yet. If you are adding LlamaKit and an issue arises because of that, please open an issue over there.

**Comment by JinkProject** [comment]
@calebd I believe ReactiveCocoa 3.0.0 uses LlamaKit and, as you said, it is written in Swift, which isn't supported by Cocoapods. Installing the pre-release of Cocoapods 0.36.0.beta.1 will downgrade ReactiveCocoa back to version 2.4.4 and remove LlamaKit.

**Comment by calebd** [comment]
Ok. ReactiveCocoa 3.0 is marked as alpha so I don't know why CocoaPods would try to install it right now. I'll push a spec update that locks the version.

**Comment by JinkProject** [comment]
:+1:

**Comment by Codeido** [comment]
With the actual version of SimpleAuth, when i try to install it, i have the following error:
```
[!] The platform of the target `Pods` (iOS 7.0) is not compatible with `ReactiveCocoa (3.0.0-alpha.1)` which has a minimum requirement of iOS 8.0 - OS X 10.9.
```
How can I fix?

**Comment by calebd** [comment]
This is a CocoaPods problem. It should not be trying to install prerelease library versions without you explicitly telling it to do so.

**Comment by Codeido** [comment]
I solved in this way, like @JinkProject 

```
pod 'ReactiveCocoa', '2.4.7'
pod 'SimpleAuth/Facebook', '0.3.6'
pod 'SimpleAuth/Twitter', '0.3.6'
```
