### ISSUE TITLE
Cannot log in into facebook-web

### ISSUE THREAD

**Issue by martinpilch** [calebd/SimpleAuth#81]
Every time I try to log in using facebook-web I'm getting:

`Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.`

The FB app is correctly setup (I can connect using FB SDK)

**Comment by calebd** [comment]
You have to change settings on the Facebook developer site. Your app is not allowed to run web login.

**Comment by martinpilch** [comment]
Thanks! That was it!
