### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by jsanders67** [calebd/SimpleAuth#83]
This may be a dumb question, but SimpleAuth does not provide a way to Authenticate instead of Authorize, right?

**Comment by calebd** [comment]
I realize the nomenclature here is a little unclear. None of the providers that SimpleAuth includes provide a means of simply determining who a user is without getting access to their account. What you get back from SimpleAuth is a user's account information as well as tokens that can be used to read and write information, depending on the user's settings, or the scope of what you ask for.

**Comment by calebd** [comment]
In the future, the `authorize` family of methods will be deprecated in favor of a new `authenticate` family of methods to fit with the preferred verb.
