### ISSUE TITLE
How remove tokens / logout user ?

### ISSUE THREAD

**Issue by iMedHelmi** [calebd/SimpleAuth#92]
Hi, I'm using SimpleAuth/FacebookWeb and SimpleAuth/TwitterWeb in my new app. I want to know what is the easiest/safest way to remove tokens in order to logout a user ? I want to be able to prompt the login interface each time and not just use stored accounts. Can you please help me figure it out ? Thanks.

**Comment by mergesort** [comment]
@iMedHelmi SimpleAuth doesn't store login tokens for you, it's up to you to know whether the user is logged in. I'd recommend storing the tokens you receive in the keychain, so not anyone can see them, and when you want to log out a user, remove them from the keychain.

**Comment by iMedHelmi** [comment]
Thank you @mergesort for your answer. The thing is, once a user is logged in, when I call [SimpleAuth authorize:@"facebook-web" completion:^(id responseObject, NSError *error)], the modal login controller is presented and immediately dismesses returning the last logged in user data. I though SimpleAuth stores somewhere the access tokens. So is it something related to cache in the webview ?

**Comment by iMedHelmi** [comment]
Hi. I ended up adding the following code to <code>SimpleAuthWebViewController</code>'s <code>viewDidLoad</code> and it worked like a charm.

<pre><code>//Set Cache
NSURLCache *sharedCache = [[NSURLCache alloc] initWithMemoryCapacity:0 diskCapacity:0 diskPath:nil];
 [NSURLCache setSharedURLCache:sharedCache];
    
//Clear All Cookies
for (NSHTTPCookie *cookie in [[NSHTTPCookieStorage sharedHTTPCookieStorage] cookies]) {
        [[NSHTTPCookieStorage sharedHTTPCookieStorage] deleteCookie:cookie];
 }</code></pre>

Thank you @mergesort :)
